// Realistic-ish seed data for a software-engineering learning platform.
// Small enough to stay well within the CognoDB free-tier (c0) limits.

const skills = [
  { id: "git", name: "Git & Version Control", category: "Foundations" },
  { id: "cli", name: "Command Line Basics", category: "Foundations" },
  { id: "html", name: "HTML", category: "Frontend" },
  { id: "css", name: "CSS", category: "Frontend" },
  { id: "js", name: "JavaScript", category: "Frontend" },
  { id: "ts", name: "TypeScript", category: "Frontend" },
  { id: "react", name: "React", category: "Frontend" },
  { id: "responsive", name: "Responsive & Accessible Design", category: "Frontend" },
  { id: "state-mgmt", name: "Frontend State Management", category: "Frontend" },
  { id: "nodejs", name: "Node.js", category: "Backend" },
  { id: "rest", name: "REST API Design", category: "Backend" },
  { id: "auth", name: "Authentication & Authorization", category: "Backend" },
  { id: "graphql", name: "GraphQL", category: "Backend" },
  { id: "testing", name: "Automated Testing", category: "Backend" },
  { id: "sql", name: "SQL", category: "Data" },
  { id: "data-modeling", name: "Relational Data Modeling", category: "Data" },
  { id: "graph-modeling", name: "Graph Data Modeling", category: "Data" },
  { id: "cypher", name: "Cypher Query Language", category: "Data" },
  { id: "python", name: "Python", category: "Data" },
  { id: "stats", name: "Statistics Fundamentals", category: "Data" },
  { id: "pandas", name: "Data Wrangling (pandas)", category: "Data" },
  { id: "ml-basics", name: "Machine Learning Basics", category: "ML" },
  { id: "linear-algebra", name: "Linear Algebra", category: "ML" },
  { id: "nlp", name: "NLP Fundamentals", category: "ML" },
  { id: "docker", name: "Docker", category: "DevOps" },
  { id: "ci-cd", name: "CI/CD Pipelines", category: "DevOps" },
  { id: "cloud-basics", name: "Cloud Fundamentals (AWS)", category: "DevOps" },
  { id: "k8s", name: "Kubernetes", category: "DevOps" },
  { id: "observability", name: "Logging & Observability", category: "DevOps" },
  { id: "sys-design", name: "System Design", category: "Architecture" },
  { id: "microservices", name: "Microservices Architecture", category: "Architecture" },
  { id: "security-basics", name: "Application Security Basics", category: "Architecture" },
  { id: "algorithms", name: "Data Structures & Algorithms", category: "Foundations" },
  { id: "ux-research", name: "UX Research Basics", category: "Frontend" },
];

// source -> target means "source is a prerequisite of target".
const prerequisites = [
  ["cli", "git"],
  ["html", "css"],
  ["html", "js"],
  ["css", "responsive"],
  ["js", "ts"],
  ["js", "react"],
  ["ts", "react"],
  ["react", "state-mgmt"],
  ["responsive", "ux-research"],
  ["js", "nodejs"],
  ["nodejs", "rest"],
  ["rest", "auth"],
  ["rest", "graphql"],
  ["nodejs", "testing"],
  ["algorithms", "sys-design"],
  ["sql", "data-modeling"],
  ["data-modeling", "graph-modeling"],
  ["graph-modeling", "cypher"],
  ["python", "pandas"],
  ["stats", "ml-basics"],
  ["pandas", "ml-basics"],
  ["linear-algebra", "ml-basics"],
  ["ml-basics", "nlp"],
  ["cli", "docker"],
  ["docker", "ci-cd"],
  ["docker", "k8s"],
  ["cloud-basics", "k8s"],
  ["ci-cd", "observability"],
  ["rest", "microservices"],
  ["k8s", "microservices"],
  ["sys-design", "microservices"],
  ["auth", "security-basics"],
  ["rest", "sys-design"],
  ["sql", "sys-design"],
];

const courses = [
  { id: "c-git-101", title: "Git & GitHub Essentials", provider: "Waypoint Academy", level: "Beginner", durationHours: 4, teaches: ["git"], requires: ["cli"] },
  { id: "c-cli-101", title: "The Command Line, Demystified", provider: "Waypoint Academy", level: "Beginner", durationHours: 3, teaches: ["cli"], requires: [] },
  { id: "c-html-css", title: "HTML & CSS from Scratch", provider: "Waypoint Academy", level: "Beginner", durationHours: 10, teaches: ["html", "css"], requires: [] },
  { id: "c-responsive", title: "Responsive & Accessible Interfaces", provider: "OpenUX", level: "Intermediate", durationHours: 6, teaches: ["responsive"], requires: ["css"] },
  { id: "c-js-core", title: "Modern JavaScript", provider: "Waypoint Academy", level: "Beginner", durationHours: 14, teaches: ["js"], requires: ["html"] },
  { id: "c-ts-core", title: "TypeScript for JS Developers", provider: "Waypoint Academy", level: "Intermediate", durationHours: 8, teaches: ["ts"], requires: ["js"] },
  { id: "c-react-core", title: "React from the Ground Up", provider: "Frontend Masters+", level: "Intermediate", durationHours: 16, teaches: ["react"], requires: ["js", "ts"] },
  { id: "c-state", title: "State Management Patterns", provider: "Frontend Masters+", level: "Advanced", durationHours: 6, teaches: ["state-mgmt"], requires: ["react"] },
  { id: "c-ux-research", title: "UX Research for Engineers", provider: "OpenUX", level: "Intermediate", durationHours: 5, teaches: ["ux-research"], requires: ["responsive"] },
  { id: "c-node-core", title: "Node.js Fundamentals", provider: "Backend Guild", level: "Intermediate", durationHours: 12, teaches: ["nodejs"], requires: ["js"] },
  { id: "c-rest", title: "Designing REST APIs", provider: "Backend Guild", level: "Intermediate", durationHours: 7, teaches: ["rest"], requires: ["nodejs"] },
  { id: "c-graphql", title: "GraphQL in Practice", provider: "Backend Guild", level: "Advanced", durationHours: 8, teaches: ["graphql"], requires: ["rest"] },
  { id: "c-auth", title: "Authentication & Authorization Patterns", provider: "Backend Guild", level: "Advanced", durationHours: 6, teaches: ["auth"], requires: ["rest"] },
  { id: "c-security", title: "Application Security Fundamentals", provider: "SecureStack", level: "Advanced", durationHours: 7, teaches: ["security-basics"], requires: ["auth"] },
  { id: "c-testing", title: "Automated Testing for Node Services", provider: "Backend Guild", level: "Intermediate", durationHours: 6, teaches: ["testing"], requires: ["nodejs"] },
  { id: "c-algorithms", title: "Data Structures & Algorithms", provider: "CS Foundations", level: "Intermediate", durationHours: 20, teaches: ["algorithms"], requires: [] },
  { id: "c-sys-design", title: "System Design Interview Prep", provider: "CS Foundations", level: "Advanced", durationHours: 12, teaches: ["sys-design"], requires: ["algorithms", "rest", "sql"] },
  { id: "c-microservices", title: "Microservices in Production", provider: "CS Foundations", level: "Advanced", durationHours: 10, teaches: ["microservices"], requires: ["sys-design", "k8s"] },
  { id: "c-sql-core", title: "SQL for Application Developers", provider: "Data Guild", level: "Beginner", durationHours: 8, teaches: ["sql"], requires: [] },
  { id: "c-data-modeling", title: "Relational Data Modeling", provider: "Data Guild", level: "Intermediate", durationHours: 6, teaches: ["data-modeling"], requires: ["sql"] },
  { id: "c-graph-modeling", title: "Graph Data Modeling Patterns", provider: "Data Guild", level: "Intermediate", durationHours: 6, teaches: ["graph-modeling"], requires: ["data-modeling"] },
  { id: "c-cypher", title: "openCypher Query Language", provider: "Data Guild", level: "Intermediate", durationHours: 5, teaches: ["cypher"], requires: ["graph-modeling"] },
  { id: "c-python-core", title: "Python for Data", provider: "Data Guild", level: "Beginner", durationHours: 10, teaches: ["python"], requires: [] },
  { id: "c-pandas", title: "Data Wrangling with pandas", provider: "Data Guild", level: "Intermediate", durationHours: 7, teaches: ["pandas"], requires: ["python"] },
  { id: "c-stats", title: "Statistics for Data Science", provider: "Data Guild", level: "Intermediate", durationHours: 9, teaches: ["stats"], requires: [] },
  { id: "c-linalg", title: "Linear Algebra Refresher", provider: "CS Foundations", level: "Intermediate", durationHours: 8, teaches: ["linear-algebra"], requires: [] },
  { id: "c-ml-basics", title: "Machine Learning Foundations", provider: "ML Collective", level: "Advanced", durationHours: 18, teaches: ["ml-basics"], requires: ["pandas", "stats", "linear-algebra"] },
  { id: "c-nlp", title: "NLP Fundamentals", provider: "ML Collective", level: "Advanced", durationHours: 12, teaches: ["nlp"], requires: ["ml-basics"] },
  { id: "c-docker", title: "Docker for Developers", provider: "DevOps Guild", level: "Intermediate", durationHours: 6, teaches: ["docker"], requires: ["cli"] },
  { id: "c-cicd", title: "CI/CD Pipelines with GitHub Actions", provider: "DevOps Guild", level: "Intermediate", durationHours: 5, teaches: ["ci-cd"], requires: ["docker"] },
  { id: "c-cloud-basics", title: "Cloud Fundamentals (AWS)", provider: "DevOps Guild", level: "Beginner", durationHours: 8, teaches: ["cloud-basics"], requires: [] },
  { id: "c-k8s", title: "Kubernetes in Practice", provider: "DevOps Guild", level: "Advanced", durationHours: 14, teaches: ["k8s"], requires: ["docker", "cloud-basics"] },
  { id: "c-observability", title: "Logging, Metrics & Observability", provider: "DevOps Guild", level: "Advanced", durationHours: 6, teaches: ["observability"], requires: ["ci-cd"] },
];

const learners = [
  { id: "l-amina", name: "Amina Yusuf", role: "Junior Frontend Engineer" },
  { id: "l-ben", name: "Ben Torres", role: "Backend Engineer" },
  { id: "l-chen", name: "Chen Wei", role: "Full-Stack Engineer" },
  { id: "l-dara", name: "Dara Fitzgerald", role: "Data Analyst" },
  { id: "l-elias", name: "Elias Novak", role: "DevOps Engineer" },
  { id: "l-farah", name: "Farah Haidari", role: "Product Engineer" },
  { id: "l-gus", name: "Gustavo Lima", role: "ML Engineer (aspiring)" },
  { id: "l-himanshu", name: "Himanshu Shinde", role: "Full-Stack Engineer" },
  { id: "l-ines", name: "Ines Duarte", role: "Frontend Engineer" },
  { id: "l-jae", name: "Jae Park", role: "Backend Engineer" },
  { id: "l-kira", name: "Kira Volkov", role: "Platform Engineer" },
  { id: "l-leo", name: "Leo Marchetti", role: "New Grad Engineer" },
];

// learnerId -> [{ skillId, proficiency }]
const knows = {
  "l-amina": [["html", "advanced"], ["css", "advanced"], ["js", "intermediate"], ["responsive", "intermediate"]],
  "l-ben": [["cli", "advanced"], ["nodejs", "advanced"], ["rest", "advanced"], ["sql", "intermediate"], ["testing", "intermediate"]],
  "l-chen": [["html", "advanced"], ["css", "advanced"], ["js", "advanced"], ["ts", "intermediate"], ["react", "intermediate"], ["nodejs", "intermediate"], ["rest", "intermediate"]],
  "l-dara": [["sql", "advanced"], ["data-modeling", "intermediate"], ["python", "intermediate"], ["pandas", "beginner"]],
  "l-elias": [["cli", "advanced"], ["docker", "advanced"], ["ci-cd", "intermediate"], ["cloud-basics", "intermediate"]],
  "l-farah": [["html", "advanced"], ["css", "advanced"], ["js", "advanced"], ["ts", "advanced"], ["react", "advanced"], ["state-mgmt", "intermediate"], ["ux-research", "beginner"]],
  "l-gus": [["python", "advanced"], ["stats", "intermediate"], ["linear-algebra", "beginner"], ["pandas", "intermediate"]],
  "l-himanshu": [["cli", "advanced"], ["git", "advanced"], ["html", "advanced"], ["css", "advanced"], ["js", "advanced"], ["ts", "intermediate"], ["react", "intermediate"], ["nodejs", "intermediate"], ["sql", "beginner"]],
  "l-ines": [["html", "advanced"], ["css", "advanced"], ["responsive", "advanced"], ["js", "intermediate"], ["ux-research", "intermediate"]],
  "l-jae": [["cli", "advanced"], ["nodejs", "advanced"], ["rest", "advanced"], ["auth", "intermediate"], ["sql", "advanced"], ["data-modeling", "intermediate"]],
  "l-kira": [["cli", "advanced"], ["docker", "advanced"], ["k8s", "intermediate"], ["cloud-basics", "advanced"], ["ci-cd", "advanced"]],
  "l-leo": [["html", "intermediate"], ["css", "intermediate"], ["js", "beginner"], ["algorithms", "beginner"]],
};

// learnerId -> [{ courseId, status, progress }]
const enrollments = {
  "l-amina": [["c-js-core", "in_progress", 60]],
  "l-chen": [["c-ts-core", "completed", 100], ["c-react-core", "in_progress", 40]],
  "l-dara": [["c-graph-modeling", "in_progress", 25]],
  "l-elias": [["c-k8s", "in_progress", 50]],
  "l-himanshu": [["c-ts-core", "in_progress", 70], ["c-sql-core", "completed", 100]],
  "l-jae": [["c-graphql", "in_progress", 30]],
  "l-leo": [["c-algorithms", "in_progress", 15]],
};

module.exports = { skills, prerequisites, courses, learners, knows, enrollments };
